### ISSUE TITLE
Not able to install on Debian 10 due to some pyqt5 error

### ISSUE THREAD

**Issue by stevavoliajvar** [Widdershin/flask-desktop#26]
I am using Debian 10, and cannot get flask-desktop to work. 

Running 
```
pip install git+git://github.com/widdershin/flask-desktop.git
```

and it gives me the next output 

```
Collecting git+git://github.com/widdershin/flask-desktop.git
  Cloning git://github.com/widdershin/flask-desktop.git to /tmp/pip-req-build-eat_z9lm
Collecting Flask==1.0 (from WebUI==0.2.1)
  Using cached https://files.pythonhosted.org/packages/55/b1/4365193655df97227ace49311365cc296e74b60c7f5c63d23cd30175e2f6/Flask-1.0-py2.py3-none-any.whl
Requirement already satisfied: Jinja2==2.10 in /usr/lib/python3/dist-packages (from WebUI==0.2.1) (2.10)
Collecting MarkupSafe==1.1.1 (from WebUI==0.2.1)
  Using cached https://files.pythonhosted.org/packages/98/7b/ff284bd8c80654e471b769062a9b43cc5d03e7a615048d96f4619df8d420/MarkupSafe-1.1.1-cp37-cp37m-manylinux1_x86_64.whl
Collecting PyQt5==5.15.0 (from WebUI==0.2.1)
  Using cached https://files.pythonhosted.org/packages/8c/90/82c62bbbadcca98e8c6fa84f1a638de1ed1c89e85368241e9cc43fcbc320/PyQt5-5.15.0.tar.gz
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-q58gk5hu/PyQt5/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-q58gk5hu/PyQt5/
```

Anyone had same issue and solved it ?

**Comment by Jasperabez** [comment]
Are you using a python virtual environment?
Using a virtual environment might be the simplest way to solve your issue, or try clearing your pip cache.
