### ISSUE TITLE
Markupsafe dependency problems.

### ISSUE THREAD

**Issue by xcodz-dot** [Widdershin/flask-desktop#31]
Here is a dependency problem that I am facing while trying to install on Ubuntu.

```
Collecting webui
  Using cached WebUI-0.1.7.zip (4.5 kB)
Requirement already satisfied: click>=7.1.2 in /home/xcodz/.local/lib/python3.8/site-packages (from flask->-r requirements.txt (line 1)) (8.0.1)
Requirement already satisfied: Jinja2>=3.0 in /home/xcodz/.local/lib/python3.8/site-packages (from flask->-r requirements.txt (line 1)) (3.0.1)
Requirement already satisfied: itsdangerous>=2.0 in /home/xcodz/.local/lib/python3.8/site-packages (from flask->-r requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: Werkzeug>=2.0 in /home/xcodz/.local/lib/python3.8/site-packages (from flask->-r requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: zope.event in /home/xcodz/.local/lib/python3.8/site-packages (from gevent->-r requirements.txt (line 2)) (4.5.0)
Requirement already satisfied: zope.interface in /home/xcodz/.local/lib/python3.8/site-packages (from gevent->-r requirements.txt (line 2)) (5.4.0)
Requirement already satisfied: greenlet<2.0,>=0.4.17; platform_python_implementation == "CPython" in /home/xcodz/.local/lib/python3.8/site-packages (from gevent->-r requirements.txt (line 2)) (1.1.0)
Requirement already satisfied: setuptools in /home/xcodz/.local/lib/python3.8/site-packages (from gevent->-r requirements.txt (line 2)) (57.0.0)
Collecting MarkupSafe==0.18
  Using cached MarkupSafe-0.18.tar.gz (11 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9fgl7zh5/MarkupSafe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9fgl7zh5/MarkupSafe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-qa7p8i3m
         cwd: /tmp/pip-install-9fgl7zh5/MarkupSafe/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9fgl7zh5/MarkupSafe/setup.py", line 3, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature' from 'setuptools' (/home/xcodz/.local/lib/python3.8/site-packages/setuptools/__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Looks more of a dependency version problem.

**Comment by Widdershin** [comment]
Thanks for the report. I'm not actively working on this project but I'd be happy to review and merge a pull request if you manage to sort the issue out.

**Comment by xcodz-dot** [comment]
yeah, some day when I will be free. I will surely look into this
