### ISSUE TITLE
ImportError: No module named QtWebKit

### ISSUE THREAD

**Issue by moithil** [Widdershin/flask-desktop#6]
The program installed with no error but when running it throws
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/moithilb/virtualenvironment/SerialApp/local/lib/python2.7/site-packages/webui/__init__.py", line 1, in <module>
    from webui import *
  File "/home/moithilb/virtualenvironment/SerialApp/local/lib/python2.7/site-packages/webui/webui.py", line 4, in <module>
    import PySide.QtWebKit as web_core
ImportError: No module named QtWebKit

```

I have found that qtwebkit has been deprecated and qtwebengine has to be used. Is there any quick workaround to solve the issue?

**Comment by Widdershin** [comment]
Try installing directly from this git repo, the webui package is out of date.

If anyone is interested in becoming the maintainer of this repo I would love to hand it off, I have no interest in supporting this library going forward.

**Comment by PiecePaperCode** [comment]
pip install PyQtWebEngine
will solve your problem
